# Generated by Django 5.2.8 on 2025-11-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Lunch'), ('snack', 'Snack'), ('dessert', 'Dessert')], default='breakfast', max_length=20),
        ),
    ]
