# Generated by Django 5.2.8 on 2025-11-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
