# Generated by Django 5.2.8 on 2025-11-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
